# Generated by Django 3.0 on 2019-12-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField(choices=[(0, '视频'), (1, '文章')], verbose_name='视频还是文章评论')),
                ('content', models.CharField(blank=True, default='', max_length=1024, verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='post.Post', verbose_name='文章id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='user.User', verbose_name='用户id')),
                ('video_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='video.Video')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='回复内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment', verbose_name='评论id')),
                ('replay_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='replay_to_user', to='user.User', verbose_name='被回复人id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_user', to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评论回复',
                'verbose_name_plural': '评论回复',
                'db_table': 'comment_reply',
            },
        ),
    ]
