# Generated by Django 3.0 on 2020-01-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('post', '0002_auto_20200106_0945'),
        ('user', '0002_auto_20200106_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=1024, verbose_name='评论内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('unlike_count', models.IntegerField(default=0, verbose_name='反对数')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='post.Post', verbose_name='文章')),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_comment', to='comment.Comment', verbose_name='引用评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='user.User', verbose_name='用户')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='video.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
    ]
