# Generated by Django 3.0 on 2019-12-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='信息发布时间')),
                ('company_name', models.CharField(max_length=128, verbose_name='公司名')),
                ('location', models.CharField(max_length=128, verbose_name='工作地点')),
                ('salary', models.CharField(max_length=128, verbose_name='工资范围')),
                ('require', models.CharField(max_length=1024, verbose_name='工作职责')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('need_exam', models.BooleanField(default=False, verbose_name='需要笔试')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_end', models.BooleanField(default=False, verbose_name='已结束')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
                'db_table': 'recruitment',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '招聘信息分类',
                'verbose_name_plural': '招聘信息分类',
                'db_table': 'recruitment_category',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('resume_tag', models.TextField(default='', verbose_name='此简历的标签')),
                ('resume_status', models.IntegerField(choices=[(0, '待处理'), (1, '已查看'), (2, '不合适'), (3, '待安排面试'), (4, '已安排面试'), (5, '已面试')], default=0, verbose_name='此简历的状态')),
                ('interview_room_id', models.CharField(default='', max_length=1024, verbose_name='面试房间id')),
                ('interview_note', models.TextField(default='', verbose_name='面试记录')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('rec_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recruitment', to='recruitment.Recruitment', verbose_name='招聘信息id')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resume_recruitment', to='user.UserResume', verbose_name='收到的简历id')),
            ],
            options={
                'verbose_name': '招聘收到的简历',
                'verbose_name_plural': '招聘收到的简历',
                'db_table': 'recruitment_resume',
            },
        ),
        migrations.AddField(
            model_name='recruitment',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recruitment_category', to='recruitment.RecruitmentCategory', verbose_name='招聘分类id'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='exam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recruitment_exam', to='exam.Exam', verbose_name='笔试题id'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_recruitment', to='user.User', verbose_name='用户id'),
        ),
    ]
