# Generated by Django 3.0 on 2020-01-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_val',
            field=models.IntegerField(default=1, verbose_name='经验值'),
        ),
        migrations.AlterField(
            model_name='user',
            name='food_num',
            field=models.IntegerField(default=10, verbose_name='辣条数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='等级'),
        ),
    ]
