# Generated by Django 3.0 on 2020-01-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200106_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthenticationinfo',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userresume',
            old_name='user_id',
            new_name='user',
        ),
    ]
