# Generated by Django 3.0 on 2020-01-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200110_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthority',
            old_name='user_id',
            new_name='user',
        ),
    ]
