# Generated by Django 3.0 on 2019-12-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='标签名')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='标签创建时间')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='创建用户id')),
            ],
            options={
                'verbose_name': '视频标签',
                'verbose_name_plural': '视频标签',
                'db_table': 'video_tag',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='视频路径')),
                ('overview_path', models.TextField(verbose_name='封面路径')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('description', models.TextField(default='', verbose_name='视频描述/简介')),
                ('tag', models.TextField(default='', verbose_name='标签')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放数')),
                ('is_ready', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核不通过')], default=0, verbose_name='审核结果')),
                ('not_ready_reason', models.CharField(default='', max_length=1024, verbose_name='审核不通过原因')),
                ('status', models.IntegerField(choices=[(0, '未转码'), (1, '转码成功'), (2, '转码失败')], default=0, verbose_name='视频状态')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('food_count', models.IntegerField(default=0, verbose_name='辣条数')),
                ('extra_data', models.TextField(default='', verbose_name='额外信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
            },
        ),
    ]
