# Generated by Django 3.0 on 2019-12-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='题目创建时间')),
                ('start_datetime', models.DateTimeField(auto_now=True, verbose_name='笔试开始时间')),
                ('end_datetime', models.DateTimeField(auto_now=True, verbose_name='笔试结束时间')),
                ('questions', models.TextField(default='', verbose_name='题目')),
                ('extra_data', models.TextField(default='', verbose_name='预留')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('create_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_exam', to='user.User', verbose_name='创建者id')),
            ],
            options={
                'verbose_name': '招聘用的笔试题',
                'verbose_name_plural': '招聘用的笔试题',
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='', verbose_name='答卷')),
                ('start_datetime', models.DateTimeField(auto_now=True, verbose_name='答题开始时间')),
                ('end_datetime', models.DateTimeField(auto_now=True, verbose_name='答题结束时间')),
                ('jump_out_count', models.IntegerField(default=0, verbose_name='用户跳出页面次数')),
                ('grade', models.IntegerField(default=-1, verbose_name='成绩')),
                ('extra_data', models.TextField(default='', verbose_name='预留')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_exam_answer', to='exam.Exam', verbose_name='笔试题id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_exam_answer', to='user.User', verbose_name='答题用户id')),
            ],
            options={
                'verbose_name': '笔试题答案表',
                'verbose_name_plural': '笔试题答案表',
                'db_table': 'exam_answer',
            },
        ),
    ]
